### ISSUE TITLE
Remove instance of "Esmail EL BoB"

### ISSUE THREAD

**Issue by xbdmHQ** [realaravinth/libmedium#20]
Esmail is actively forbidding members or supporters of the LGBTQIA+ community to use their services via a TOS document*.
This is absolutely queerphobic and extremely discriminating. Therefore I ask to remove their instance https://libmedium.esmailelbob.xyz from the list, to not further support their actions.

*See the commit here: [EsmailELBoBDev2/upptime@c46b9bf](https://github.com/EsmailELBoBDev2/upptime/commit/c46b9bfd03b211dff2b87737da2de33629685a5a) -> https://web.archive.org/web/20230522041632/https://github.com/EsmailELBoBDev2/upptime/commit/c46b9bfd03b211dff2b87737da2de33629685a5a

**Comment by realaravinth** [comment]
Thanks for bringing this up. Can you please send a PR as well?

---

Hello @EsmailELBoBDev2,

In a word that is so full of hatred, love of any kind is beautiful and must be celebrated. I hope you realize this someday, until then I have to remove your instance from this list.

**Comment by xbdmHQ** [comment]
> Thanks for bringing this up. Can you please send a PR as well?
> 
> Hello @EsmailELBoBDev2,
> 
> In a word that is so full of hatred, love of any kind is beautiful and must be celebrated. I hope you realize this someday, until then I have to remove your instance from this list.

You didn't remove it

**Comment by realaravinth** [comment]
Sorry for the misunderstanding, I was asking if you could send a PR removing their instance. I will do it myself :+1:

**Comment by EsmailELBoBDev2** [comment]
> love of any kind is beautiful and must be celebrated

Sure! love your pet, love your family. Love is good but when turns to be harmful, un-logical and ***FORBIDDEN*** in my religion then no, it's not beautiful.

I hope you too understand that, there are people with different point of views, and, idk maybe someday you will learn how to accept other different opinions (instead of shadow ban and hack).
___
PS: @xbdmHQ @magiclike get a life instead of open 420 issues to silence me.
